require('dotenv').config();
const mongoose = require('mongoose');
const Skill = require('./models/Skill');
const Question = require('./models/Question');

const SKILLS = [
  'Arrays', 'Strings', 'Linked Lists', 'Stacks', 'Queues',
  'Trees', 'Graphs', 'Binary Search', 'Dynamic Programming',
];

const QUESTIONS = [
  // ===================== ARRAYS =====================
  { skill: 'Arrays', difficulty: 'easy', text: 'What is the time complexity of accessing an element by index in an array?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], answer: 0, explanation: 'Array index access is O(1) due to contiguous memory allocation.' },
  { skill: 'Arrays', difficulty: 'easy', text: 'What is the worst-case time complexity of insertion at the beginning of an array of size n?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n log n)'], answer: 0, explanation: 'All n existing elements must shift right when inserting at index 0.' },
  { skill: 'Arrays', difficulty: 'easy', text: 'Which of the following is a key advantage of an array over a linked list?', options: ['Random access in O(1)', 'Dynamic resizing without overhead', 'Constant time insertion anywhere', 'No memory fragmentation'], answer: 0, explanation: 'Arrays provide O(1) constant time random access via indices.' },
  { skill: 'Arrays', difficulty: 'medium', text: 'Which algorithm finds a pair summing to a target in a sorted array in O(n) time and O(1) space?', options: ['Two pointers', 'Brute force', 'DFS', 'Dijkstra'], answer: 0, explanation: 'Two pointers move inwards from both ends in a sorted array.' },
  { skill: 'Arrays', difficulty: 'medium', text: 'What algorithm finds the maximum subarray sum in O(n) time?', options: ["Kadane's Algorithm", 'Binary Search', "Floyd's Algorithm", "Dijkstra's Algorithm"], answer: 0, explanation: "Kadane's algorithm computes max subarray sum in a single linear pass." },
  { skill: 'Arrays', difficulty: 'medium', text: 'How can you find the majority element (> n/2 occurrences) in O(n) time and O(1) space?', options: ["Boyer-Moore Voting Algorithm", 'Sort and return middle', 'Hash map count', 'Binary search'], answer: 0, explanation: 'Boyer-Moore Voting finds the majority candidate in O(n) time and O(1) auxiliary space.' },
  { skill: 'Arrays', difficulty: 'medium', text: 'In the sliding window technique on an array, what is the typical overall time complexity?', options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2^n)'], answer: 0, explanation: 'Both window pointers traverse the array at most once, taking O(n) total time.' },
  { skill: 'Arrays', difficulty: 'hard', text: 'What is the auxiliary space complexity of standard merge sort on an array?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], answer: 0, explanation: 'Merge sort on arrays requires O(n) auxiliary memory for the temporary merge buffer.' },
  { skill: 'Arrays', difficulty: 'hard', text: 'In the Trapping Rain Water problem on an elevation array, what is the optimal time and space complexity?', options: ['O(n) time, O(1) space', 'O(n²) time, O(1) space', 'O(n log n) time, O(n) space', 'O(1) time, O(n) space'], answer: 0, explanation: 'Using the two-pointer approach, trapping rain water can be solved in O(n) time and O(1) space.' },

  // ===================== STRINGS =====================
  { skill: 'Strings', difficulty: 'easy', text: 'Which data structure/type is immutable in languages like Java, Python, and JavaScript?', options: ['String', 'Array', 'Linked List', 'Stack'], answer: 0, explanation: 'Strings are immutable in Java/Python/JS for security, caching, and thread safety.' },
  { skill: 'Strings', difficulty: 'easy', text: 'What is the time complexity of checking if a string of length n is a palindrome using two pointers?', options: ['O(n)', 'O(n²)', 'O(1)', 'O(log n)'], answer: 0, explanation: 'Checking palindrome compares characters from both ends in at most n/2 steps, which is O(n).' },
  { skill: 'Strings', difficulty: 'easy', text: 'What does a valid anagram check between two strings typically require?', options: ['Identical character frequency counts', 'Same substring ordering', 'Same length only', 'Same first and last character'], answer: 0, explanation: 'Anagrams are permutations containing the exact same frequency of each character.' },
  { skill: 'Strings', difficulty: 'medium', text: 'What is the time complexity of the KMP pattern matching algorithm for text n and pattern m?', options: ['O(n + m)', 'O(n × m)', 'O(n²)', 'O(m²)'], answer: 0, explanation: 'KMP precomputes the LPS prefix table in O(m) and matches in O(n), giving O(n + m).' },
  { skill: 'Strings', difficulty: 'medium', text: 'What is the space-efficient technique to find the longest palindromic substring in O(n²) time and O(1) space?', options: ['Expand around center', 'Brute force all substrings', 'Prefix sum array', 'Topological sort'], answer: 0, explanation: 'Expanding around 2n-1 possible centers finds palindromes in O(n²) time with O(1) extra space.' },
  { skill: 'Strings', difficulty: 'medium', text: 'Which specialized tree data structure is optimal for prefix-based string searching and autocomplete?', options: ['Trie (Prefix Tree)', 'Binary Search Tree', 'Segment Tree', 'Fenwick Tree'], answer: 0, explanation: 'A Trie stores common prefixes efficiently and supports O(k) lookup where k is string length.' },
  { skill: 'Strings', difficulty: 'hard', text: 'What is the time complexity of constructing a Suffix Automaton or Suffix Tree using Ukkonen’s algorithm?', options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(n³)'], answer: 0, explanation: "Ukkonen's algorithm constructs a suffix tree in linear O(n) time." },
  { skill: 'Strings', difficulty: 'hard', text: "Which algorithm finds the longest palindromic substring in strictly linear O(n) time?", options: ["Manacher's Algorithm", "KMP Algorithm", "Rabin-Karp Algorithm", "Boyer-Moore Algorithm"], answer: 0, explanation: "Manacher's algorithm utilizes palindrome symmetry to find the longest palindrome in O(n) time." },

  // ===================== LINKED LISTS =====================
  { skill: 'Linked Lists', difficulty: 'easy', text: 'What is the time complexity of inserting a node at the head of a singly linked list?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], answer: 0, explanation: 'Head insertion only requires updating the new node’s next pointer and head pointer in O(1).' },
  { skill: 'Linked Lists', difficulty: 'easy', text: 'What is a major drawback of a singly linked list compared to an array?', options: ['No random access (sequential access only)', 'Fixed capacity', 'Higher cache locality', 'Cannot grow dynamically'], answer: 0, explanation: 'Linked lists require O(n) sequential traversal to reach the k-th node.' },
  { skill: 'Linked Lists', difficulty: 'medium', text: 'Which technique detects a cycle in a linked list using O(1) extra space?', options: ["Floyd's Tortoise and Hare algorithm", 'Hash Set of visited nodes', 'Recursion stack', 'Sorting nodes'], answer: 0, explanation: "Floyd's cycle detection uses slow (1 step) and fast (2 steps) pointers with O(1) memory." },
  { skill: 'Linked Lists', difficulty: 'medium', text: 'How do you find the middle node of a singly linked list in a single pass?', options: ['Fast and slow pointer approach', 'Count nodes then traverse half', 'Convert to array', 'Reverse the list'], answer: 0, explanation: 'When the fast pointer (moving 2x) reaches the end, the slow pointer is at the middle.' },
  { skill: 'Linked Lists', difficulty: 'medium', text: 'What is the time complexity to reverse a singly linked list iteratively?', options: ['O(n) time and O(1) space', 'O(n²) time and O(1) space', 'O(n) time and O(n) space', 'O(log n) time and O(1) space'], answer: 0, explanation: 'Reversing with prev, curr, and next pointers takes 1 pass: O(n) time and O(1) space.' },
  { skill: 'Linked Lists', difficulty: 'hard', text: 'What is the optimal time complexity to merge k sorted linked lists with N total nodes?', options: ['O(N log k)', 'O(N × k)', 'O(N²)', 'O(k log N)'], answer: 0, explanation: 'Using a min-heap of size k, each of the N nodes is extracted in O(log k) time.' },
  { skill: 'Linked Lists', difficulty: 'hard', text: 'In Floyd’s cycle detection, if a cycle of length C exists and the distance to the cycle start is L, where do the pointers meet after resetting slow to head?', options: ['At the start of the cycle', 'At the end of the list', 'At node L/2', 'They never meet'], answer: 0, explanation: 'Moving both pointers at speed 1 from head and meeting point guarantees meeting at the cycle entrance.' },

  // ===================== STACKS =====================
  { skill: 'Stacks', difficulty: 'easy', text: 'Which data access principle does a Stack follow?', options: ['LIFO (Last In, First Out)', 'FIFO (First In, First Out)', 'Random Access', 'Priority based'], answer: 0, explanation: 'A stack strictly allows push/pop operations from the top, adhering to LIFO.' },
  { skill: 'Stacks', difficulty: 'easy', text: 'What error occurs when attempting to pop an element from an empty stack?', options: ['Stack Underflow', 'Stack Overflow', 'Segmentation Fault', 'Memory Leak'], answer: 0, explanation: 'Popping from an empty stack causes stack underflow.' },
  { skill: 'Stacks', difficulty: 'medium', text: 'Which classic problem is most naturally solved using a stack?', options: ['Valid Parentheses matching', 'Shortest path in weighted graph', 'Binary search', 'Minimum spanning tree'], answer: 0, explanation: 'Validating nested brackets/parentheses uses a stack to match the most recent opening bracket.' },
  { skill: 'Stacks', difficulty: 'medium', text: 'What technique solves the "Next Greater Element" problem on an array in O(n) time?', options: ['Monotonic Stack', 'Binary Search', 'Two Pointers', 'Breadth-First Search'], answer: 0, explanation: 'A monotonic decreasing stack keeps elements in order and finds next greater in linear time.' },
  { skill: 'Stacks', difficulty: 'medium', text: 'How can you evaluate an arithmetic expression in Reverse Polish Notation (Postfix)?', options: ['Push operands to stack; pop on operator and push result', 'Use BFS queue', 'Binary search tree', 'Two pointers'], answer: 0, explanation: 'Postfix evaluation pushes operands and evaluates pairs when an operator is encountered.' },
  { skill: 'Stacks', difficulty: 'hard', text: 'What is the amortized time complexity per operation in a MinStack that supports push, pop, and getMin in O(1)?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(√n)'], answer: 0, explanation: 'Maintaining a parallel min-value stack allows getMin in constant O(1) time.' },
  { skill: 'Stacks', difficulty: 'hard', text: 'What is the optimal time complexity to find the Largest Rectangle in a Histogram using a stack?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(n!)'], answer: 0, explanation: 'A monotonic increasing stack computes the max rectangle in a single O(n) pass.' },

  // ===================== QUEUES =====================
  { skill: 'Queues', difficulty: 'easy', text: 'Which data access principle does a standard Queue follow?', options: ['FIFO (First In, First Out)', 'LIFO (Last In, First Out)', 'Random Access', 'Sorted order only'], answer: 0, explanation: 'Queues enqueue at the rear and dequeue from the front (FIFO).' },
  { skill: 'Queues', difficulty: 'easy', text: 'What is the time complexity of enqueue and dequeue in an efficient queue implementation?', options: ['O(1) for both', 'O(n) for both', 'O(1) enqueue, O(n) dequeue', 'O(log n) for both'], answer: 0, explanation: 'Using head/tail pointers or a circular buffer, both operations run in O(1).' },
  { skill: 'Queues', difficulty: 'medium', text: 'Which graph and tree traversal algorithm fundamentally relies on a queue?', options: ['Breadth-First Search (BFS)', 'Depth-First Search (DFS)', 'Inorder Traversal', 'Postorder Traversal'], answer: 0, explanation: 'BFS processes nodes level-by-level using a FIFO queue.' },
  { skill: 'Queues', difficulty: 'medium', text: 'What data structure allows efficient insertion and deletion from both the front and the rear in O(1)?', options: ['Deque (Double-Ended Queue)', 'Standard Queue', 'Stack', 'Priority Queue'], answer: 0, explanation: 'A Deque supports push/pop at both front and back in O(1) time.' },
  { skill: 'Queues', difficulty: 'medium', text: 'How can a queue be implemented using two stacks with amortized O(1) operations?', options: ['Push to stack1; pop from stack2 (transfer when stack2 is empty)', 'Push to both stacks simultaneously', 'Alternate pushes between stacks', 'Use recursion on stack1'], answer: 0, explanation: 'Elements transfer to stack2 only when stack2 is empty, yielding amortized O(1) dequeue.' },
  { skill: 'Queues', difficulty: 'hard', text: 'Which queue variant efficiently solves the "Sliding Window Maximum" problem in O(n) total time?', options: ['Monotonic Deque', 'Min-Heap Priority Queue', 'Circular Array', 'Two-Stack Queue'], answer: 0, explanation: 'A monotonic decreasing deque maintains candidate maximums in O(1) amortized time per element.' },
  { skill: 'Queues', difficulty: 'hard', text: 'What is the time complexity of extracting the minimum element from a Fibonacci Heap?', options: ['O(log n) amortized', 'O(1) strictly', 'O(n) strictly', 'O(n log n)'], answer: 0, explanation: 'Delete-min in a Fibonacci heap takes O(log n) amortized time while insert and decrease-key take O(1).' },

  // ===================== TREES =====================
  { skill: 'Trees', difficulty: 'easy', text: 'What is the maximum number of nodes at level L in a binary tree (where root is level 0)?', options: ['2^L', '2L', 'L²', '2^(L+1)'], answer: 0, explanation: 'Each level doubles node capacity: level 0 has 1 (2^0), level 1 has 2 (2^1), level L has 2^L.' },
  { skill: 'Trees', difficulty: 'easy', text: 'In which tree traversal are nodes visited in the order: Root -> Left Subtree -> Right Subtree?', options: ['Preorder', 'Inorder', 'Postorder', 'Level-order'], answer: 0, explanation: 'Preorder traversal visits Root first, then Left, then Right.' },
  { skill: 'Trees', difficulty: 'easy', text: 'In a Binary Search Tree (BST), what traversal produces elements in strictly ascending sorted order?', options: ['Inorder (Left -> Root -> Right)', 'Preorder', 'Postorder', 'Breadth-First'], answer: 0, explanation: 'Inorder traversal of a valid BST always visits keys in sorted order.' },
  { skill: 'Trees', difficulty: 'medium', text: 'What is the height of a balanced Binary Search Tree with n nodes?', options: ['O(log n)', 'O(n)', 'O(√n)', 'O(1)'], answer: 0, explanation: 'A balanced BST (AVL or Red-Black) maintains a height bounded by O(log n).' },
  { skill: 'Trees', difficulty: 'medium', text: 'What is the lowest common ancestor (LCA) of nodes p and q in a BST if root.val is between p.val and q.val?', options: ['The current root node', 'The left child of root', 'The right child of root', 'The root of the whole tree always'], answer: 0, explanation: 'In a BST, the split point where p and q diverge on left/right is their LCA.' },
  { skill: 'Trees', difficulty: 'medium', text: 'Which property defines an AVL tree?', options: ['The height difference between left and right subtrees of any node is at most 1', 'Every level is completely filled except possibly the last', 'Every node has either 0 or 2 children', 'All leaf nodes are at the exact same depth'], answer: 0, explanation: 'An AVL tree is height-balanced with a balance factor of -1, 0, or +1 at every node.' },
  { skill: 'Trees', difficulty: 'hard', text: 'What is the time complexity of finding the Lowest Common Ancestor (LCA) in a general binary tree?', options: ['O(n)', 'O(log n) always', 'O(1)', 'O(n²)'], answer: 0, explanation: 'In an unbalanced general binary tree, searching for LCA takes O(n) time to traverse all nodes.' },
  { skill: 'Trees', difficulty: 'hard', text: 'How do you serialize and deserialize a binary tree in optimal O(n) time?', options: ['Preorder traversal with null markers (sentinels)', 'Inorder traversal alone', 'Postorder traversal alone without markers', 'Adjacency matrix'], answer: 0, explanation: 'Preorder traversal with null placeholders uniquely encodes the tree structure in O(n) time.' },

  // ===================== GRAPHS =====================
  { skill: 'Graphs', difficulty: 'easy', text: 'Which graph representation is most space-efficient for a sparse graph with V vertices and E edges?', options: ['Adjacency List: O(V + E)', 'Adjacency Matrix: O(V²)', 'Incidence Matrix: O(V × E)', 'Complete Edge Matrix'], answer: 0, explanation: 'An adjacency list stores only existing edges, requiring O(V + E) space.' },
  { skill: 'Graphs', difficulty: 'easy', text: 'Which algorithm finds the shortest path in an unweighted graph?', options: ['Breadth-First Search (BFS)', 'Depth-First Search (DFS)', 'Kruskal Algorithm', 'Prim Algorithm'], answer: 0, explanation: 'BFS expands uniformly by edge count, guaranteeing shortest path in unweighted graphs.' },
  { skill: 'Graphs', difficulty: 'medium', text: 'What is the time complexity of Dijkstra’s algorithm using a Min-Heap / Priority Queue?', options: ['O((V + E) log V)', 'O(V²)', 'O(E²)', 'O(V × E)'], answer: 0, explanation: 'Heap operations cost log V per vertex/edge update, resulting in O((V + E) log V).' },
  { skill: 'Graphs', difficulty: 'medium', text: 'Which algorithm produces a topological sort of a Directed Acyclic Graph (DAG)?', options: ["Kahn's Algorithm (in-degree BFS) or DFS with stack", "Dijkstra's Algorithm", "Floyd-Warshall Algorithm", "Prim's Algorithm"], answer: 0, explanation: "Kahn's in-degree BFS and DFS post-order both produce valid topological orders on DAGs." },
  { skill: 'Graphs', difficulty: 'medium', text: 'How can you detect a cycle in a directed graph using DFS?', options: ['Check for a back-edge to a vertex currently in the recursion stack (visiting state)', 'Check if a vertex is visited twice in any order', 'Count total edge degrees', 'Run BFS once'], answer: 0, explanation: 'A cycle in a directed graph corresponds to a back-edge into an ancestor in the current DFS stack.' },
  { skill: 'Graphs', difficulty: 'hard', text: 'Which algorithm finds all-pairs shortest paths in O(V³) time and handles negative edge weights without negative cycles?', options: ['Floyd-Warshall Algorithm', "Dijkstra's Algorithm", "Kruskal's Algorithm", 'Kosaraju Algorithm'], answer: 0, explanation: 'Floyd-Warshall uses dynamic programming to compute all-pairs distances in O(V³).' },
  { skill: 'Graphs', difficulty: 'hard', text: "Which algorithm finds Strongly Connected Components (SCCs) in a directed graph in O(V + E) time using two DFS passes?", options: ["Kosaraju's Algorithm", "Bellman-Ford Algorithm", "Boruvka's Algorithm", "Edmonds-Karp Algorithm"], answer: 0, explanation: "Kosaraju's algorithm uses DFS on the original graph and transposed graph to find all SCCs in O(V + E)." },

  // ===================== BINARY SEARCH =====================
  { skill: 'Binary Search', difficulty: 'easy', text: 'What essential precondition must be satisfied before applying Binary Search on an array?', options: ['The elements must be sorted (or monotonic)', 'The array must contain only unique elements', 'The array size must be a power of 2', 'The array must be stored on a linked list'], answer: 0, explanation: 'Binary search requires sorted/monotonic data to discard half the search space at each step.' },
  { skill: 'Binary Search', difficulty: 'easy', text: 'What is the time complexity of Binary Search on a sorted array of size n?', options: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'], answer: 0, explanation: 'Each iteration divides the search space in half, running in O(log n) time.' },
  { skill: 'Binary Search', difficulty: 'medium', text: 'How should you calculate the middle index in binary search to prevent integer overflow in languages with fixed-width integers?', options: ['mid = low + (high - low) / 2', 'mid = (low + high) / 2', 'mid = (low * high) / 2', 'mid = high / 2'], answer: 0, explanation: 'low + (high - low) / 2 avoids integer overflow when low + high exceeds INT_MAX.' },
  { skill: 'Binary Search', difficulty: 'medium', text: 'In a sorted array with duplicates, how do you find the first occurrence of target if arr[mid] == target?', options: ['Set high = mid - 1 (or search left half) and record index', 'Set low = mid + 1', 'Return mid immediately', 'Terminate search'], answer: 0, explanation: 'To find the first occurrence (lower bound), continue searching left even after finding a match.' },
  { skill: 'Binary Search', difficulty: 'medium', text: 'What is the time complexity of searching for an element in a sorted rotated array without duplicates?', options: ['O(log n)', 'O(n)', 'O(√n)', 'O(n log n)'], answer: 0, explanation: 'At least one half is always strictly sorted, allowing modified binary search in O(log n).' },
  { skill: 'Binary Search', difficulty: 'hard', text: 'What technique is used to solve the "Capacity to Ship Packages Within D Days" or "Split Array Largest Sum"?', options: ['Binary Search on the Answer (Predicate / Monotonic search space)', 'Dynamic Programming O(n³)', 'Greedy without search', 'Graph BFS'], answer: 0, explanation: 'Binary search over the answer range [max(arr), sum(arr)] tests feasibility monotonically in O(n log(sum)).' },
  { skill: 'Binary Search', difficulty: 'hard', text: 'What is the time complexity to find the median of two sorted arrays of sizes m and n?', options: ['O(log(min(m, n)))', 'O(m + n)', 'O((m + n) log(m + n))', 'O(1)'], answer: 0, explanation: 'Binary search on the partition index of the smaller array finds the median in O(log(min(m, n))).' },

  // ===================== DYNAMIC PROGRAMMING =====================
  { skill: 'Dynamic Programming', difficulty: 'easy', text: 'What two core properties characterize problems solvable by Dynamic Programming?', options: ['Optimal Substructure and Overlapping Subproblems', 'Greedy choice and sorted input', 'No subproblems and independent states', 'Linear time and constant space'], answer: 0, explanation: 'DP applies when optimal subproblem solutions compose the global optimum and subproblems recur.' },
  { skill: 'Dynamic Programming', difficulty: 'easy', text: 'What is the primary difference between Memoization and Tabulation?', options: ['Memoization is top-down with recursion/caching; Tabulation is bottom-up iterative', 'Memoization is bottom-up; Tabulation is top-down', 'Tabulation uses exponential space; Memoization uses O(1)', 'They are identical with different names'], answer: 0, explanation: 'Memoization caches recursive calls top-down; Tabulation iteratively populates a DP table bottom-up.' },
  { skill: 'Dynamic Programming', difficulty: 'medium', text: 'What is the time and space complexity of computing the nth Fibonacci number using bottom-up DP with 2 variables?', options: ['O(n) time and O(1) space', 'O(2^n) time and O(n) space', 'O(n) time and O(n) space', 'O(1) time and O(n) space'], answer: 0, explanation: 'Iteratively storing just the previous two values requires O(n) time and O(1) auxiliary space.' },
  { skill: 'Dynamic Programming', difficulty: 'medium', text: 'What is the time complexity of the 0/1 Knapsack Problem with n items and maximum capacity W using Tabulation?', options: ['O(n × W)', 'O(2^n)', 'O(n + W)', 'O(n!)'], answer: 0, explanation: 'The 2D DP table has dimensions (n + 1) × (W + 1), resulting in pseudo-polynomial O(n × W) time.' },
  { skill: 'Dynamic Programming', difficulty: 'medium', text: 'What is the time complexity to find the Longest Common Subsequence (LCS) of two strings of lengths m and n?', options: ['O(m × n)', 'O(m + n)', 'O(2^(m+n))', 'O(m² + n²)'], answer: 0, explanation: 'The standard 2D DP table for LCS compares characters across m × n states in O(m × n) time.' },
  { skill: 'Dynamic Programming', difficulty: 'hard', text: 'What is the optimal time complexity to find the Longest Increasing Subsequence (LIS) of an array of size n?', options: ['O(n log n) using patience sorting / binary search on tails', 'O(n²) using simple DP only', 'O(2^n) brute force', 'O(n) linear'], answer: 0, explanation: 'Maintaining the tails array and updating via binary search reduces LIS computation from O(n²) to O(n log n).' },
  { skill: 'Dynamic Programming', difficulty: 'hard', text: 'What is the time complexity of Matrix Chain Multiplication for n matrices using dynamic programming?', options: ['O(n³)', 'O(n²)', 'O(2^n)', 'O(n log n)'], answer: 0, explanation: 'Matrix Chain Multiplication evaluates O(n²) subproblem intervals, each taking O(n) split checks = O(n³).' },
];

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/learnsmart';
  await mongoose.connect(uri);
  console.log('Connected to MongoDB');

  await Skill.deleteMany({});
  await Question.deleteMany({});

  await Skill.insertMany(SKILLS.map((name) => ({ name, description: `${name} fundamentals for DSA` })));
  await Question.insertMany(QUESTIONS);

  console.log(`Seeded ${SKILLS.length} skills and ${QUESTIONS.length} questions successfully`);
  await mongoose.disconnect();
}

// Export for automatic bootstrapping if needed
module.exports = { seed, QUESTIONS, SKILLS };

if (require.main === module) {
  seed().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
